name: api_mongodb
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  mongo_dart: ^0.7.0+1

dev_dependencies:
  http: ^0.13.0
  test: ^1.15.0
  test_process: ^2.0.0
# comandos para subir o docker
# docker build -t lucascardo12/service_fcm:latest -f Dockerfile . 
# docker push lucascardo12/service_fcm:latest  